baseURL = "https://tarasmatsyk.com/"
languageCode = "en-us"
title = "Taras Matsyk"
theme = "sustain"
highlight = true

[params]
  avatar = "profile.png"
  author = "Taras Matsyk"
  description = "Taras Matsyk is a software engineer, indie hacker, open source contributor, surfer and public speaker"

[params.social]
  Github        = "tarasmatsyk"
  Email         = "hello@tarasmatsyk.com"
  Twitter       = "tarasmatsyk"
  LinkedIn      = "tarasmatsyk"
  Stackoverflow = "users/3727348/taras-matsyk?tab=profile"
  Facebook      = "tamatsyk"
  Keybase       = "tarasmatsyk"
