baseURL = "https://tarasmatsyk.com/"
languageCode = "en-us"
title = "Taras Matsyk"
theme = "hyde-hyde"
highlight = true
disqusShortname = "tarasmatsyk-com"
googleAnalytics = "UA-129700443-1"

[params]
    description = 'Only code can judge me'
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    copyright = "© 2018 Taras Matsyk"
    themeColor = "theme-base-0d"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 10
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 20
    url = "/about/"


[params.social]
    github = "tarasmatsyk"
    instagram = "tarasmatsyk"
    linkedin = "tarasmatsyk"
    twitter = "tarasmatsyk"
    stackoverflow = "3727348/taras-matsyk?tab=profile"
    telegram = "tarasmatsyk"
    email = "tamatsyk@gmail.com"
    gravatar = "tamatsyk@gmail.com"

[params.meta]
    description = "Taras Matsyk is a software engineer, open-source contributor, an indie hacker and a public speaker."
    keywords = "Python,Architecture,Machine Learning,JavaScript"
