baseURL = "https://tarasmatsyk.com/"
languageCode = "en-us"
title = "Taras Matsyk"
theme = "hyde"
highlight = true
# disqusShortname = "your-disqus-shortname"
googleAnalytics = "UA-129700443-1"

[params]
    author = "Taras"
    description = "np.array[Python • JS]^Vim © only code can judge me"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    copyright = "© 2018 Taras Matsyk"
    themeColor = "theme-base-0d"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 10
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 20
    url = "/about/"


[params.social]
    github = "tarasmatsyk"
    instagram = "tarasmatsyk"
    linkedin = "tarasmatsyk"
    twitter = "tarasmatsyk"
    stackoverflow = "users/3727348/taras-matsyk?tab=profile"
    telegram = "tarasmatsyk"
    email = "hello@tarasmatsyk.com"
